#!/bin/sh
base=/var/www
read request

while /bin/true; do
  read header
  [ "$header" == $'\r' ] && break;
done
url="${request#GET }"
url="${url% HTTP/*}"
filename="$base$url"
if [ -f "$filename" ]; then
  echo -e "HTTP/1.1 200 OK\r"
  echo -e "Content-Type: `/usr/bin/file -bi \"$filename\"`\r"
  echo -e "\r"
  cat "$filename"
  echo -e "\r"
else
  echo -e "HTTP/1.1 404 Not Found\r"
  echo -e "Content-Type: text/html\r"
  echo -e "\r"
  echo -e "404 Not Found\r"
  echo -e "Not Found
           The requested resource was not found\r"
  echo -e "\r"
fi

#为了使它工作，你必须添加以下行到/etc/inetd.conf文件：
#www stream tcp nowait nobody /usr/local/bin/webd webd
#使用/etc/init.d/inetd restart使脚本生效后

